GET http://localhost:3000/Ad?category=voit
###
POST http://localhost:3000/Ad
Content-Type: application/json

{
    "title": "une voiture ptn",
    "description":
    "Ceci est une voiture",
    "owner": "Voiture man",
    "price": 5000,
    "picture":
    "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Lyon",
    "createdAt": "2023-10-05T10:14:15.922Z",
    "category": 2
}
###
POST http://localhost:3000/Ad
Content-Type: application/json

{
    "title": "TEST 4",
    "owner": "Dieu himself"
}
###
DELETE http://localhost:3000/Ad/3
###
PATCH http://localhost:3000/Ad/4
Content-Type: application/json

{
    "title": "TEST TEST",
    "description": "TEST marche enfin cette merde ptn j'ai le bareau"
}