GET http://localhost:3000/Ad
###
GET http://localhost:3000/Ad/sort/desc
###
GET http://localhost:3000/Ad/filter/voiture
###
POST http://localhost:3000/Ad
Content-Type: application/json

{
    "title": "HOUSE to sell",
    "description":
    "My HOUSE is blue, working fine. I'm selling it because I've got a new one",
    "owner": "Le pape",
    "price": 100000,
    "picture":
    "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Marseille",
    "createdAt": "2023-10-05T10:14:15.922Z",
    "category": 3
}
###
POST http://localhost:3000/Ad
Content-Type: application/json

{
    "title": "HOUSE to sell",
    "owner": "Le pape"
}
###
DELETE http://localhost:3000/Ad/3
###
PATCH http://localhost:3000/Ad/3
Content-Type: application/json

{
    "title": "J'ai le BAREAU PTN",
    "description": "ça marche enfin cette merde ptn j'ai le bareau"
}