GET http://localhost:5000/Category?name=
###
POST http://localhost:5000/Category
Content-Type: application/json

{
    "name": "Vacances"
}
###
DELETE http://localhost:5000/Category/4
###
PATCH http://localhost:5000/Category/3
Content-Type: application/json

{
    "name": "Autre"
}