GET http://localhost:5000/Tag?name=
###
POST http://localhost:5000/Tag
Content-Type: application/json

{
    "name": "tag numero 4"
}
###
DELETE http://localhost:5000/Tag/4
###
PATCH http://localhost:5000/Tag/5
Content-Type: application/json

{
    "name": "couleur bleue"
}